# Generated by Django 3.0.6 on 2020-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.CharField(default='qqq', max_length=100),
            preserve_default=False,
        ),
    ]
